Tracker:AddLocations("locations/Dan's Crypt.json")
Tracker:AddLocations("locations/Graveyard.json")
Tracker:AddLocations("locations/Cemetery Hill.json")
Tracker:AddLocations("locations/Hilltop Mausoleum.json")
Tracker:AddLocations("locations/Return to the Graveyard.json")
Tracker:AddLocations("locations/Scarecrow Fields.json")
Tracker:AddLocations("locations/Pumpkin Gorge.json")
Tracker:AddLocations("locations/Pumpkin Serpent.json")
Tracker:AddLocations("locations/Sleeping Village.json")
Tracker:AddLocations("locations/Asylum Grounds.json")
Tracker:AddLocations("locations/Inside the Asylum.json")
Tracker:AddLocations("locations/Enchanted Earth.json")
Tracker:AddLocations("locations/Ant Caves.json")
Tracker:AddLocations("locations/Pools of the Ancient Dead.json")
Tracker:AddLocations("locations/Lake.json")
Tracker:AddLocations("locations/Crystal Caves.json")
Tracker:AddLocations("locations/Gallows Gauntlet.json")
Tracker:AddLocations("locations/Haunted Ruins.json")
Tracker:AddLocations("locations/Ghost Ship.json")
Tracker:AddLocations("locations/Entrance Hall.json")
Tracker:AddLocations("locations/Time Device.json")